Repository nhom7net/cinestream, pull requests merged in 2024-11, with the labels that each got.

#3 fix(gh): quên bỏ vào thư mục
  .github/workflows/vercel-merge.yml
  .github/workflows/vercel-pr.yml
Labels: bug

#11 Chức năng tìm kiếm bộ phim
  package-lock.json
  src/components/MovieCard.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/[genreSlug]/+page.svelte
Labels: enhancement

#15 [HOTFIX] Fix lỗi không tự điều hướng sau khi đăng ký
  src/routes/auth/+page.server.ts
Labels: enhancement

#16 Lưu lịch sử tập phim đã xem
  src/routes/details/[movieSlug]/+page.svelte
  src/routes/details/[movieSlug]/+page.ts
  src/routes/history/+page.server.ts
  src/routes/history/+page.svelte
  src/routes/history/+page.ts
Labels: enhancement

#21 Tính năng Lưu/Yêu thích phim
  src/routes/bookmark/+page.server.ts
  src/routes/bookmark/+page.svelte
  src/routes/details/[movieSlug]/+page.server.ts
  src/routes/details/[movieSlug]/+page.svelte
  src/routes/details/[movieSlug]/+page.ts
Labels: Tính năng mới
