Repository nhom7net/cinestream, pull requests merged in 2024-12, with the labels that each got.

#29 [Cải thiện] Class cho việc gửi thông báo Toast
  src/lib/ToastNotification.ts
Labels: Cải thiện

#31 Chỉnh sửa css cho phần lịch sử phim
  src/routes/history/+page.svelte
Labels: Cải thiện

#33 Cho phép thay đổi mật khẩu trên trang profile
  package.json
  pnpm-lock.yaml
  src/hooks.server.ts
  src/routes/+layout.ts
  src/routes/profile/+page.server.ts
  src/routes/profile/+page.svelte
  src/routes/profile/templates/Account.svelte
  src/routes/profile/templates/Profile.svelte
Labels: Cải thiện

#39 xong trang quản lý bình luận
  src/routes/admin/comment/+page.server.ts
  src/routes/admin/comment/+page.svelte
Labels: Tính năng mới

#41 fix lỗi nhập lung tung phần search
  src/routes/admin/comment/+page.svelte
Labels: Lỗi

#42 [ADMIN] Chức năng quản lý người dùng
  src/app.postcss
  src/lib/Avatar.svelte
  src/lib/UserInfo.svelte
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+layout.ts
  src/routes/admin/+page.server.ts
  src/routes/admin/+page.svelte
  src/routes/admin/comment/+page.server.ts
  src/routes/admin/comment/+page.svelte
  src/routes/admin/user/+page.server.ts
  src/routes/admin/user/+page.svelte
Labels: Tính năng mới

#44 thêm phần bình luận bị báo cáo trong admin
  src/routes/admin/comment/+page.server.ts
  src/routes/admin/comment/+page.svelte
Labels: Cải thiện

#43 chuc nang trang phat phim
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/routes/details/[movieSlug]/+page.svelte
  src/routes/watch/[watchSlug]/+page.svelte
  src/routes/watch/[watchSlug]/+page.ts
Labels: Tính năng mới

#45 Tính năng đánh giá & bình luận phim
  src/routes/details/[movieSlug]/+page.svelte
Labels: Tính năng mới

#47 chỉnh sửa giao diện quản lý bình luận đồng bộ với quản lý người dùng
  src/routes/admin/comment/+page.server.ts
  src/routes/admin/comment/+page.svelte
Labels: Cải thiện

#46 thay đổi giao diện bình luận, bỏ time và thêm avatar
  src/routes/details/[movieSlug]/+page.server.ts
  src/routes/details/[movieSlug]/+page.svelte
  src/routes/details/[movieSlug]/+page.ts
Labels: Cải thiện
